stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  tags:
    - tag
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  tags:
    - tag
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  tags:
    - tag
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  tags:
    - tag
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

